apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmqlistenerack
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: rabbitmqlistenerack-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: rabbitmqlistenerack-app
    spec:
      containers:
      - name: rabbitmqlistenerack-pod
        image: shanepeckham/rabbitmqlistenerack:v8
        ports:
        - containerPort: 8080
        env:
        - name: TEAMNAME
          value: "team3"
        - name: RABBITMQHOST
          value: "amqp://guest:guest@k8steam3rab-rabbitmq.default.svc.cluster.local:5672"
        - name: PARTITIONKEY
          value: "1" 
        - name: PROCESSENDPOINT 
          value: "http://fulfillorder.[namespace].svc.cluster.local:8080/v1/order/"
